
// @todo handle these in the reducer
export const NOTE_LOADING_STATUS_TRUE = 'NOTE_LOADING_STATUS_TRUE';
export const NOTE_LOADING_STATUS_FALSE = 'NOTE_LOADING_STATUS_FALSE';
export const NOTE_LOGIN_PROBLEM = 'NOTE_LOGIN_PROBLEM';
export const FORGET_LOGIN_PROBLEMS = 'FORGET_LOGIN_PROBLEMS';
export const NOTE_USER_DATA_GATHERING_PROBLEM = 'NOTE_USER_DATA_GATHERING_PROBLEM';
export const FORGET_USER_DATA_GATHERING_PROBLEMS = 'FORGET_USER_DATA_GATHERING_PROBLEMS';
export const NOTE_CURRENT_USER_INFO = 'NOTE_CURRENT_USER_INFO';
export const FORGET_SIGNUP_PROBLEMS = 'FORGET_SIGNUP_PROBLEMS';
export const NOTE_SIGNUP_PROBLEM = 'NOTE_SIGNUP_PROBLEM';
//export const  = '';
//export const  = '';
//export const  = '';

